/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.Controlador;
import java.awt.Color;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author alberto
 */
public class RegistroBD extends javax.swing.JFrame {

    String nombreBD, usuario, pass;
    public static int numeroMesas;

    /**
     * Creates new form RegistroBD
     */
    public RegistroBD() {
        initComponents();
        setLocationRelativeTo(null);
        btnEjemplo.setVisible(false);
        txtMesas.addKeyListener(new KeyAdapter() {
            public void keyTyped(KeyEvent e) {
                char caracter = e.getKeyChar();
                if (((caracter < '0') || (caracter > '9')) && (caracter != '\b') || txtMesas.getText().length()>=3) {
                    e.consume();
                }
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblLogo = new javax.swing.JLabel();
        lblNombreBD = new javax.swing.JLabel();
        txtNombreBD = new javax.swing.JTextField();
        lblUsuario = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        lblPass = new javax.swing.JLabel();
        txtPass = new javax.swing.JTextField();
        btnRegistrarBD = new javax.swing.JButton();
        lblResultado = new javax.swing.JLabel();
        btnSalir = new javax.swing.JButton();
        btnEjemplo = new javax.swing.JButton();
        txtMesas = new javax.swing.JTextField();
        lblMesas = new javax.swing.JLabel();
        lblFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblLogo.setBackground(new java.awt.Color(187, 187, 187));
        lblLogo.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        lblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logo.png"))); // NOI18N
        getContentPane().add(lblLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, 280, 290));

        lblNombreBD.setBackground(new java.awt.Color(255, 255, 255));
        lblNombreBD.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        lblNombreBD.setForeground(new java.awt.Color(255, 255, 255));
        lblNombreBD.setText("<html>Este será el nombre de la base de datos, por ejemplo, el nombre de tu negocio</html>");
        getContentPane().add(lblNombreBD, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, 380, 70));

        txtNombreBD.setBackground(new java.awt.Color(255, 255, 255));
        txtNombreBD.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        txtNombreBD.setForeground(new java.awt.Color(0, 0, 0));
        txtNombreBD.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtNombreBDFocusGained(evt);
            }
        });
        txtNombreBD.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNombreBDKeyReleased(evt);
            }
        });
        getContentPane().add(txtNombreBD, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 360, 180, 30));

        lblUsuario.setBackground(new java.awt.Color(255, 255, 255));
        lblUsuario.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        lblUsuario.setForeground(new java.awt.Color(255, 255, 255));
        lblUsuario.setText("Nombre de usuario principal");
        getContentPane().add(lblUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 480, 280, 20));

        txtUsuario.setBackground(new java.awt.Color(255, 255, 255));
        txtUsuario.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        txtUsuario.setForeground(new java.awt.Color(0, 0, 0));
        txtUsuario.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtUsuarioFocusGained(evt);
            }
        });
        getContentPane().add(txtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 510, 180, 30));

        lblPass.setBackground(new java.awt.Color(255, 255, 255));
        lblPass.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        lblPass.setForeground(new java.awt.Color(255, 255, 255));
        lblPass.setText("Contraseña de usuario principal");
        getContentPane().add(lblPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 550, 290, 20));

        txtPass.setBackground(new java.awt.Color(255, 255, 255));
        txtPass.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        txtPass.setForeground(new java.awt.Color(0, 0, 0));
        txtPass.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtPassFocusGained(evt);
            }
        });
        txtPass.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtPassKeyPressed(evt);
            }
        });
        getContentPane().add(txtPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 580, 180, 30));

        btnRegistrarBD.setBackground(new java.awt.Color(204, 204, 204));
        btnRegistrarBD.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        btnRegistrarBD.setForeground(new java.awt.Color(0, 0, 0));
        btnRegistrarBD.setText("Registrar");
        btnRegistrarBD.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnRegistrarBD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarBDActionPerformed(evt);
            }
        });
        getContentPane().add(btnRegistrarBD, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 630, 80, 40));

        lblResultado.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        lblResultado.setForeground(Color.RED);
        getContentPane().add(lblResultado, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 650, 200, 30));

        btnSalir.setBackground(new java.awt.Color(255, 102, 102));
        btnSalir.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        btnSalir.setForeground(new java.awt.Color(255, 255, 255));
        btnSalir.setText("X");
        btnSalir.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        getContentPane().add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 0, 30, 30));

        btnEjemplo.setBackground(new java.awt.Color(204, 204, 204));
        btnEjemplo.setFont(new java.awt.Font("Consolas", 1, 12)); // NOI18N
        btnEjemplo.setForeground(new java.awt.Color(0, 0, 0));
        btnEjemplo.setText("Ver ejemplo");
        btnEjemplo.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnEjemplo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEjemploActionPerformed(evt);
            }
        });
        getContentPane().add(btnEjemplo, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 360, 100, 30));

        txtMesas.setBackground(new java.awt.Color(255, 255, 255));
        txtMesas.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        txtMesas.setForeground(new java.awt.Color(0, 0, 0));
        txtMesas.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtMesasFocusGained(evt);
            }
        });
        getContentPane().add(txtMesas, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 430, 180, 30));

        lblMesas.setBackground(new java.awt.Color(255, 255, 255));
        lblMesas.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        lblMesas.setForeground(new java.awt.Color(255, 255, 255));
        lblMesas.setText("Número de mesas que tienes");
        getContentPane().add(lblMesas, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 400, -1, -1));

        lblFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/login.jpg"))); // NOI18N
        getContentPane().add(lblFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 410, 710));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistrarBDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarBDActionPerformed
        comprueba();
    }//GEN-LAST:event_btnRegistrarBDActionPerformed

    private void txtNombreBDFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNombreBDFocusGained
        txtNombreBD.setBackground(Color.WHITE);
        lblResultado.setText("");
    }//GEN-LAST:event_txtNombreBDFocusGained

    private void txtUsuarioFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtUsuarioFocusGained
        txtUsuario.setBackground(Color.WHITE);
        lblResultado.setText("");
    }//GEN-LAST:event_txtUsuarioFocusGained

    private void txtPassFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPassFocusGained
        txtPass.setBackground(Color.WHITE);
        lblResultado.setText("");
    }//GEN-LAST:event_txtPassFocusGained

    private void txtPassKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPassKeyPressed
        if (evt.getKeyCode() == 10) {
            comprueba();
        }
    }//GEN-LAST:event_txtPassKeyPressed


    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnEjemploActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEjemploActionPerformed
        EjemploBD ejemploBD = new EjemploBD();
        ejemploBD.setVisible(true);
        ejemploBD.ponerNombre(txtNombreBD.getText());
    }//GEN-LAST:event_btnEjemploActionPerformed

    private void txtNombreBDKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreBDKeyReleased
        if (txtNombreBD.getText().length() != 0) {
            btnEjemplo.setVisible(true);
        } else {
            btnEjemplo.setVisible(false);
        }

        if (evt.getKeyCode() == 10) {
            comprueba();
        }
    }//GEN-LAST:event_txtNombreBDKeyReleased

    private void txtMesasFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtMesasFocusGained
        txtMesas.setBackground(Color.WHITE);
        txtMesas.setText("");
    }//GEN-LAST:event_txtMesasFocusGained

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistroBD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistroBD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistroBD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistroBD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistroBD().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEjemplo;
    private javax.swing.JButton btnRegistrarBD;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel lblFondo;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblMesas;
    private javax.swing.JLabel lblNombreBD;
    private javax.swing.JLabel lblPass;
    private javax.swing.JLabel lblResultado;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JTextField txtMesas;
    private javax.swing.JTextField txtNombreBD;
    private javax.swing.JTextField txtPass;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables

    private void comprueba() {
        if (!txtUsuario.getText().isEmpty() && !txtPass.getText().isEmpty() && !txtNombreBD.getText().isEmpty()) {
            nombreBD = txtNombreBD.getText().trim();
            usuario = txtUsuario.getText().trim();
            pass = txtPass.getText().trim();
            int respuesta = JOptionPane.showConfirmDialog(this, "¿Estás seguro?  " + nombreBD + " será el nombre de la Base de datos", "Confirmar datos", 0, JOptionPane.QUESTION_MESSAGE);
            if (respuesta == 0) {
                if (txtMesas.getText().isEmpty()) {
                    numeroMesas = 1;
                } else {
                    numeroMesas = Integer.parseInt(txtMesas.getText());
                }
                Controlador.iniciarBD(nombreBD, usuario, pass);
                dispose();
            }

        } else if (txtPass.getText().isEmpty() && txtUsuario.getText().isEmpty() && txtNombreBD.getText().isEmpty()) {
            txtPass.setBackground(Color.RED);
            txtUsuario.setBackground(Color.RED);
            txtNombreBD.setBackground(Color.red);
            lblResultado.setText("Campos vacios");
        } else if (txtUsuario.getText().isEmpty()) {
            txtUsuario.setBackground(Color.RED);
            lblResultado.setText("Usuario vacio");
        } else if (txtPass.getText().isEmpty()) {
            txtPass.setBackground(Color.RED);
            lblResultado.setText("Contraseña vacia");
        } else if (txtNombreBD.getText().isEmpty()) {
            txtNombreBD.setBackground(Color.RED);
            lblResultado.setText("Nombre de la BD vacio");
        }
    }
}
